# Generated by Django 2.1.4 on 2018-12-29 08:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('departmentCode', models.CharField(max_length=5)),
                ('website', models.URLField()),
                ('designation', models.CharField(max_length=50)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
        ),
    ]
