# Generated by Django 2.1.4 on 2018-12-29 19:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webview', '0002_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='finalRatings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance', models.DecimalField(decimal_places=2, max_digits=3)),
                ('grade', models.DecimalField(decimal_places=2, max_digits=3)),
                ('ta', models.DecimalField(decimal_places=2, max_digits=3)),
                ('timing', models.DecimalField(decimal_places=2, max_digits=3)),
                ('tags', models.TextField()),
                ('professor', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='finalRatingprof', to='webview.Professor')),
                ('subject', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='finalRatingUser', to='webview.Subject')),
            ],
        ),
        migrations.CreateModel(
            name='rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('professor', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='prof', to='webview.Professor')),
                ('subject', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='subject', to='webview.Subject')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
