# Generated by Django 2.1.4 on 2018-12-30 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webview', '0004_auto_20181230_0310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finalratings',
            name='attendance',
            field=models.DecimalField(decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='finalratings',
            name='grade',
            field=models.DecimalField(decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='finalratings',
            name='numAttendance',
            field=models.IntegerField(default=1, null=True),
        ),
        migrations.AlterField(
            model_name='finalratings',
            name='numGrade',
            field=models.IntegerField(default=1, null=True),
        ),
        migrations.AlterField(
            model_name='finalratings',
            name='numTa',
            field=models.IntegerField(default=1, null=True),
        ),
        migrations.AlterField(
            model_name='finalratings',
            name='numTiming',
            field=models.IntegerField(default=1, null=True),
        ),
        migrations.AlterField(
            model_name='finalratings',
            name='ta',
            field=models.DecimalField(decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='finalratings',
            name='timing',
            field=models.DecimalField(decimal_places=2, max_digits=3, null=True),
        ),
    ]
